Add Terraform check workflow
TakeScoop/.github pull request #19
Opened 2021-07-13 16:49 UTC by ryanwholey

Adds a workflow to format check, validate and lint terraform modules as seen in the [terraform-aws-transit-gateway](https://github.com/TakeScoop/terraform-aws-transit-gateway/blob/master/.github/workflows/lint-check-validate.yaml) repo

2021-07-13 18:43 UTC, bendrucker requested changes

2021-07-13 18:43 UTC, bendrucker commented on workflow-templates/check-terraform-module.yml
> +        package: ${{ fromJson(needs.find-modules.outputs.matrix) }}
should be module, here and in the `lint` job, no "package" in TF

2021-07-13 18:43 UTC, bendrucker commented on workflow-templates/check-terraform-module.yml
> +        uses: ryanwholey/remote-tflint-config@v2
Let's get this into the `terraform-linters` org before merging this template. Can give you comments on the action itself as part of that move.

2021-07-13 18:43 UTC, bendrucker commented on workflow-templates/check-terraform-module.yml
> +            --config ${{ steps.fetch-tflint-config.outputs.path }}
```suggestion
            --config "${{ steps.fetch-tflint-config.outputs.path }}"
```

2021-07-13 18:43 UTC, bendrucker commented on workflow-templates/check-terraform-module.properties.json
> +  "name": "check-terraform-module",
Filename should probably be `check-terraform-modules.yml` given that the monorepo functionality is a key part of the workflow. Also begs the question of whether we should be using this workflow for root modules too, monorepo bits included. If we had a pipeline w/ Terraform applying before a deploy, that probably demands a separate, partially overlapping workflow. But for now I think this makes sense to use even for root modules.

2021-07-13 18:44 UTC, ryanwholey commented on workflow-templates/check-terraform-module.yml
> +        uses: ryanwholey/remote-tflint-config@v2
lmk when and how and i'm down

2021-07-13 19:04 UTC, bendrucker commented on workflow-templates/check-terraform-module.yml
> +        uses: ryanwholey/remote-tflint-config@v2
Created https://github.com/terraform-linters/tflint-load-config-action/ and invited you. Won't be a transfer per se but you can push there. If you wanna do an init PR I can do a round of review then.

2021-07-13 19:05 UTC, ryanwholey commented on workflow-templates/check-terraform-module.yml
> +        uses: ryanwholey/remote-tflint-config@v2
perfect! thanks!

2021-07-22 20:19 UTC, ryanwholey commented on workflow-templates/check-terraform-module.properties.json
> +  "name": "check-terraform-module",
When developing this I had tested it with a find-modules action that output subdirectories and the root directory, so I believe it should work for root modules too. If it doesn't we can fix, I think it makes sense to use the same action for both casess

2021-07-22 20:41 UTC, bendrucker approved these changes

2021-07-22 20:45 UTC, merged