Add single and multi workspace workflows
TakeScoop/.github pull request #35
Opened 2021-09-08 21:43 UTC by ryanwholey

Adds two workflows, one for a single workspace and one for multi-environment workspaces

2021-09-08 21:50 UTC, ryanwholey commented on workflow-templates/terraform-workspace-multiple.yml
> +  checks: write
I _think_ this is all we need? The workspace action itself doesn't depend on any GItHub APIs, the "write check" action does, and should just need write check perms

2021-09-08 23:50 UTC, bendrucker requested changes
File*names* will be important 😉 , otherwise LGTM

2021-09-08 23:50 UTC, bendrucker commented on workflow-templates/terraform-workspace-multiple.yml
> +  checks: write
Seems correct, if the workflow uses `actions/checkout` then I include `contents: read`, but that doesn't apply here. 

> When the permissions key is used, all unspecified permissions are set to no access, with the exception of the metadata scope, which always gets read access.

So even sourcing the workspace description from the repo description would not require additional permissions.

2021-09-08 23:50 UTC, bendrucker commented on workflow-templates/terraform-workspace-multiple.yml
> +on:
Probably worth specifying the name, otherwise I think the file base name becomes the workflow name

2021-09-08 23:50 UTC, bendrucker commented on workflow-templates/terraform-workspace-multiple.properties.json
> +{
Since the template determines the filename in the repo, single/multiple ends up as a weird artifact of the workflow template implementation. It's a little subtle, but maybe `-workspace` and `workspaces`? The subtlety doesn't leave this repo. The template properties can have additional qualifiers in the name/description, those end up as display only, with no impact on usage.

2021-09-08 23:50 UTC, bendrucker commented on workflow-templates/terraform-workspace-multiple.properties.json
> +{
Fairly important actually, with the templates including `paths`. AFAICT, as is the workflows would never run if you tried to add them as is.

2021-09-09 01:13 UTC, bendrucker approved these changes

2021-09-09 01:39 UTC, merged